version: "3"
services:
  teste-kolmeya-app:
    container_name: teste-kolmeya-app
    build:
      context: .
      dockerfile: .docker/local/Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/app
    networks:
      - shared
    depends_on:
      - teste-kolmeya-db
  teste-kolmeya-db:
    container_name: teste-kolmeya-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: America/Sao_Paulo
    volumes:
      - .docker/local/data/mysql:/var/lib/mysql
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    networks:
      - shared
networks:
  shared:
    driver: bridge
